#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00

#SBATCH --job-name=app-plot-epochs
#SBATCH --ntasks-per-node=1
#SBATCH --mem=20G
#SBATCH --time=00:15:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report

singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
